version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: user-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  post-db:
    image: postgres:14-alpine
    container_name: post-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_service
    volumes:
      - post_db_data:/var/lib/postgresql/data
      - ./post-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: user_service
      GRPC_PORT: 50051
      TOKEN_TYPE: ${TOKEN_TYPE:-simple}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-here}
    ports:
      - "50051:50051"
    networks:
      - app-network

  post-service:
    build:
      context: .
      dockerfile: post-service/Dockerfile
    container_name: post-service
    depends_on:
      post-db:
        condition: service_healthy
    environment:
      DB_HOST: post-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: post_service
      PORT: 50052
    ports:
      - "50052:50052"
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - user-service
      - post-service
    environment:
      USER_SERVICE_ADDR: user-service:50051
      POST_SERVICE_ADDR: post-service:50052
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-here}
    ports:
      - "8080:8080"
    networks:
      - app-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: service-tests
    networks:
      - app-network
    depends_on:
      - api-gateway
      - user-service
      - post-service
      - postgres
    profiles:
      - test

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  post_db_data: