version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: user-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: user_service
      GRPC_PORT: 50051
      TOKEN_TYPE: ${TOKEN_TYPE:-simple}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-here}
    ports:
      - "50051:50051"
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - user-service
    environment:
      USER_SERVICE_ADDR: user-service:50051
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - app-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: service-tests
    networks:
      - app-network
    depends_on:
      - api-gateway
      - user-service
      - postgres
    profiles:
      - test

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: